# Generated by Django 5.0.3 on 2024-04-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('event_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='post_images/')),
                ('lunar_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
