# Generated by Django 5.0.3 on 2024-04-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_post',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='post_images/'),
        ),
    ]
