# Generated by Django 4.2.11 on 2024-04-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_b_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lunar_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
