# Generated by Django 4.2.11 on 2024-04-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_quote_yvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgGrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('alt', models.CharField(blank=True, max_length=60, null=True)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.imggrp')),
            ],
        ),
    ]
