# Generated by Django 4.2.11 on 2024-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_imggrp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='author_images/'),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='b_post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='b_post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.tag'),
        ),
    ]
