# Generated by Django 4.2.11 on 2024-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_tag_remove_author_user_author_image_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_post',
            name='abstract',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='b_post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
