# Generated by Django 4.2.11 on 2024-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_b_post_abstract_alter_b_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_post',
            name='author',
        ),
        migrations.AddField(
            model_name='b_post',
            name='authors',
            field=models.ManyToManyField(related_name='posts', to='blogs.author'),
        ),
    ]
