# Generated by Django 4.2.11 on 2024-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_b_post_author_b_post_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_post',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='b_cover_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='team_images/'),
        ),
    ]
