# Generated by Django 4.2.11 on 2024-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_b_post_cover_image_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_post',
            name='authors',
            field=models.ManyToManyField(blank=True, to='blogs.author'),
        ),
    ]
