# Generated by Django 4.2.11 on 2024-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_alter_b_post_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_post',
            name='authors',
            field=models.ManyToManyField(related_name='posts', to='blogs.author'),
        ),
        migrations.AlterField(
            model_name='b_post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blogs.tag'),
        ),
    ]
