# Generated by Django 4.2.11 on 2024-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_link',
            field=models.URLField(null=True),
        ),
    ]
