# Generated by Django 4.2.11 on 2024-04-22 18:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_event_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='imggrp',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
